### ISSUE TITLE
Token is currently not allowed Error 

### ISSUE THREAD

**Issue by kennisnutz** [PatrickAlphaC/defi-stake-yield-brownie-freecode#11]
Omg It was my ignorance

**Comment by Markkop** [comment]
I was having the same error for the test `test_get_user_total_value_with_different_tokens`.
The problem was that I've coded the `return false` from `isAllowedToken` inside the `for` loop, so it was returning `False` after the first loop instead of looping trough all allowedTokens.
If somebody else is having this issue, check if your `return`s are correct in the `isAllowedToken` solidity function:

```solidity
    function tokenIsAllowed(address _token) public view returns (bool) {
        for (
            uint256 allowedTokensIndex = 0;
            allowedTokensIndex < allowedTokens.length;
            allowedTokensIndex++
        ) {
            if (allowedTokens[allowedTokensIndex] == _token) {
                return true;
            }
            // don't return false here 
        }
        return false;
    }
```

**Comment by PatrickAlphaC** [comment]
Closing for now, thanks both for adding your info!
